services:
  web:
    build: .
    command: gunicorn SwapHub.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-swaphub_ru}
      - POSTGRES_USER=${DB_USER:-vladimirbragin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-Mark2022}

volumes:
  postgres_data:
  static_volume:
  media_volume:
