# Generated by Django 5.0.2 on 2025-03-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Город или адрес', max_length=255),
        ),
    ]
