# Generated by Django 5.0.2 on 2025-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('sports', 'Спорт и отдых'), ('tools', 'Инструменты'), ('home', 'Товары для дома'), ('books', 'Книги'), ('toys', 'Игрушки'), ('vehicles', 'Транспорт'), ('other', 'Другое')], default='other', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступна для аренды'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, help_text='Город или адрес', max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена аренды (руб/день)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
