name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: swaphub_ru
          POSTGRES_USER: vladimirbragin
          POSTGRES_PASSWORD: Mark2022
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run migrations
      env:
        DEBUG: 'True'
        SECRET_KEY: 'test-key-for-ci'
        DB_NAME: swaphub_ru
        DB_USER: vladimirbragin
        DB_PASSWORD: Mark2022
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        python manage.py migrate
        
    - name: Run tests
      env:
        DEBUG: 'True'
        SECRET_KEY: 'test-key-for-ci'
        DB_NAME: swaphub_ru
        DB_USER: vladimirbragin
        DB_PASSWORD: Mark2022
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        python manage.py test
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/swaphub:latest
